### ISSUE TITLE
Example in README doesn't work

### ISSUE THREAD

**Issue by blinry** [neovim/node-client#273] opened 2023-12-14 10:50 UTC
Hey :)

When we tried to run the provided example in the README (in TypeScript), we encountered three issues:

- Overwriting "nvim.window" gave us a type error. We solved this by just assigning to a local variable.
- Using the provided tests, the check that `lines` should be `[""]` failed for us. It actually was equal to `[]`.
- We got the error "`nvim_proc.disconnect()` is not a function". Not sure yet why.

Can you reproduce these errors?

**Comment by justinmk** [comment] 2024-01-13 14:54
If you can provide an example that works, please send a PR.

Duplicate of https://github.com/neovim/node-client/issues/154 https://github.com/neovim/node-client/issues/41

**Closed by justinmk** 2024-01-13 14:54 UTC

**Comment by justinmk** [comment] 2024-02-07 01:29
> When we tried to run the provided example in the README (in TypeScript), we encountered three issues:


After https://github.com/neovim/node-client/pull/309 the README.md now provides a fully working self-contained example. You should be able to copy-paste the code and run it immediately.
